name: web_view_tts
description: Add Text-To-Speech Support in Flutter WebView  for Android
version: 0.0.1
homepage: https://github.com/rohitsangwan01/web_view_tts
repository: https://github.com/rohitsangwan01/web_view_tts
issue_tracker: https://github.com/rohitsangwan01/web_view_tts/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^5.4.3+7
  flutter_tts: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/android_tts.js
  plugin:
    platforms:
      android:
        package: com.rohit.web_view_tts
        pluginClass: WebViewTtsPlugin
